server:
  port: 8102


spring:
  application:
    name: amrengp
  datasource:
      # mongodb
    data:
      mongodb:
      uri: mongodb://localhost:27017/test


#  thymeleaf:
#      cache: false
#      mode: HTML5
#      encoding: UTF-8
#      content-type: text/html

mybatis:
  mapper-locations: classpath*:mapper/*.xml,classpath*:mapper/*/*.xml
  type-aliases-package: com.amrengp.web.dao,com.gp.generator.domain

#设置静态资源路径，多个以逗号分隔
spring.resources.static-locations: classpath:static/,file:static/

logging:
  config: classpath:logback.xml
  level:
    org.springframework.web: warn

#  最近通过springboot 程序实现阿里云发送邮件问题，本地测试没有问题，部署到服务器上就报如下错误：
#  com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.qq.com, 25; timeout -1;
#  经过查找资料得知，阿里云处于安全考虑，TCP 25 端口出方向默认被封禁。
#  解决方法是邮箱的配置改为ssl加密465端口。
# email config
spring.mail.host: smtp.qq.com
spring.mail.username: xxxxxxx@qq.com
spring.mail.password: tbuduuzetdiabcji
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true
spring.mail.properties.mail.smtp.starttls.required: true
# 阿里云邮件发送问题解决配置如下
spring.mail.properties.mail.smtp.timeout: 25000
spring.mail.properties.mail.smtp.ssl.enable: true
spring.mail.properties.mail.smtp.socketFactory.port: 465
spring.mail.properties.mail.smtp.port: 465
spring.mail.properties.mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
